# Continuous integration and building of the
# PDF files using the GitHub Actions
# 1) checkout
name: CI

on:
  push:
    branches:
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile Latex Document
        uses: xu-cheng/texlive-action@v3
        with:
          os: debian
          run: |
            export DEBIAN_FRONTEND=noninteractive
            apt-get update -y
            apt-get install -y make
            make archive.zip
      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: pdfs
          path: archive.zip
